name: shoes_shop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  google_fonts: ^2.2.0
  page_transition: ^2.0.4
  badges: ^2.0.2
  awesome_dialog: ^2.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
 